### ISSUE TITLE
issuances - owner transfers from segwit addresses not working

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#1075]
It seems that segwit addresses are unable to transfer ownership of an asset to a different address.

Here is a CP transaction which is supposed to transfer the TESTTRANSFER asset ownership to `mvThcDEbeqog2aJ7JNj1FefUPaNdYYGqHt`
https://blockstream.info/testnet/tx/d07ce9432bac09870a4df46088d0a8e9917ec169117e9dd03e7a163ce90226ae

**Comment by cryptcoin-junkey** [comment]
@jdogresorg Hello. Did you find more information about this issue?

I also get a similar issue on Monaparty (not the genuine Counterparty).
In my case, I can't transfer the asset's ownership issued by base58 address to bech32 address also.

**Comment by cryptcoin-junkey** [comment]
I inspect and I got the issue reported above differ from this issue.
I fixed my issue on the Monaparty fork.
https://github.com/monaparty/counterparty-lib/commit/8a2df6b9412d41bd097603d366c62466b9c05436

I didn't add a hard-fork switch because `segwit_support` is not enabled on Monaparty mainnnet.
It may be required to add on Counterparty.

**Comment by jdogresorg** [comment]
@cryptcoin-junkey Finally getting around to fixing this issue... seems that pull #1166 should resolve the issue... doing some testing now and hope to merge the PR later this week

**Comment by jdogresorg** [comment]
closed with commit f26d0f7
