### ISSUE TITLE
XCP/BTC orders

### ISSUE THREAD

**Issue by ElvisDead** [CounterpartyXCP/counterparty-lib#1114]
Have opened xcp orders to sell for btc already more 2 months for each of three.
https://xchain.io/tx/1542828
https://xchain.io/tx/1524391
https://xchain.io/tx/1506114
It's looking like done and filled up, but still open.

**Comment by jdogresorg** [comment]
There is no issue here... there is just a lack of understanding by you of how the DEX works.

BTC can not be escrowed by the DEX therefore to buy something on the DEX with BTC, it requires you to watch for order matches and send payment for the order match within 20 blocks or the order match expires.

What you are seeing here is people who placed buy orders to buy something with BTC, and then did not send the BTC within 20 blocks, and so the order matches expired.... this is not something broken or wrong... the DEX is acting as it should.

You should be using freewallet.io desktop wallet to place orders to BUY with BTC on the dex.... if your looking to SELL something on the DEX for BTC, then you will probably see some orders like this where people who do not use Freewallet.io place buy orders on the DEX and then when the order matches, they fail to send the BTC, and so the order match expires.

The "completed" orders are the ones where someone used freewallet.io which automatically sends the BTC when it detects an order match.

I would suggest NOT using BTC on the DEX unless you use freewallet.io and the Auto-BTCpay feature, and realize there is still some risk since the BTC payment has to be sent within 20 blocks of the match... you could send the BTC and the mempool could get busy and your transaction could not arrive in time, the end result would be that you could send the BTC, have the order still expire because the BTC did not arrive in time.... 99% of the time this is not the case, but still some risk.
