### ISSUE TITLE
Skipping asset owner sanity check on numeric asset issuances

### ISSUE THREAD

**Issue by B0BSmiths** [CounterpartyXCP/counterparty-lib#1245]
The payload below can be used to create an "invalid" transaction using the CP API

{
    "method": "create_issuance",
    "params": {
        "source": "1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev",
        "asset": "A02222222222222222222",
        "quantity": 1,
        "description": "This will create an invalid transaction",
        "allow_unconfirmed_inputs": true,
        "fee": 1000,
        "extended_tx_info": true
    },
    "jsonrpc": "2.0",
    "id": 0
}

The transaction must be signed by the source and the broadcast for Counterparty to then flag it as invalid. 

It seems a sanity check on updating assets you do not own is missing or being bypassed.

Also not the leading 0 in the asset is dropped by Counterparty resulting in the transaction referring to an assets owned by another address

**Comment by jdogresorg** [comment]
core issue here is the asset name is being changed from what is provided in the API

API request uses A02222222222222222222
![image](https://github.com/CounterpartyXCP/counterparty-lib/assets/376028/27a55ecd-4de2-4697-a3c5-f6990a990bb7)

Generated CP transaction uses A2222222222222222222 (the zero disappears)
![image](https://github.com/CounterpartyXCP/counterparty-lib/assets/376028/542bc676-5cda-42e0-b128-aaac6cc95504)

Transaction fails on parsing
https://xchain.io/tx/2511174

Same thing happens when trying A03333333333333333333 ... A033 gets converted to A333

API Request uses A03333333333333333333
![image](https://github.com/CounterpartyXCP/counterparty-lib/assets/376028/8ed7b7ad-b190-4f96-8fcd-753648b03a6a)

Generated CP Transaction uses A33333333333333333333
![image](https://github.com/CounterpartyXCP/counterparty-lib/assets/376028/51451037-478f-4c92-b422-630d9ab653bd)

Transaction Fails : https://xchain.io/tx/2511175

These transactions ultimately fail, which is the correct behavior. However, we should figure out why the asset name is changing and get that fixed, so that we prevent (whenever possible) generation of issuances which will ultimately fail on parsing

**Comment by jdogresorg** [comment]
fix in pull request #1260

**Comment by jdogresorg** [comment]
Fix looks good in testing. Now an error is thrown instead of a transaction which will fail.

![image](https://github.com/CounterpartyXCP/counterparty-lib/assets/376028/b359b158-6b20-483a-a3f5-a8e12990fa69)

**Comment by jdogresorg** [comment]
closing... fix will be in 9.60.3 release
