### ISSUE TITLE
Kill `undolog`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1330]
Apparently there's this thing called the "undo_log" and it scares the hell out of me. e.g.
![telegram-cloud-photo-size-1-4985775995327982744-y](https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/f12faf5f-29d5-46b1-8122-a7a6f4d09132)

_a priori_ we should be relying on the extremely simple `rollback` logic to handle things like reorgs:
![telegram-cloud-photo-size-1-4985775995327982745-y](https://github.com/CounterpartyXCP/counterparty-lib/assets/6189829/01312a86-5017-4d4e-89ba-fcb8d0a8f96d)

This functionality is dangerous, unnecessary and completely untested. Quite possibly the cause of consensus breaks.

**Comment by jotapea** [comment]
If is not really needed, delete.

**Comment by adamkrellenstein** [comment]
If there's a bug report out there for the crashes that occurred without it, I'd love to see it. But yeah this is the wrong solution in any case.

**Comment by ouziel-slama** [comment]
I found the issue originally from the "undolog" (https://github.com/CounterpartyXCP/counterparty-lib/issues/763). I think we made a mistake in analyzing the problem at the time. As a reminder, the problem is that during a reorg we restart all the transactions. If we do this it is only because of the `balance` table which does not have a `block_index` field.
The `balance` table is only a reflection of the `credit` and `debit` tables. So there is no problem rebuilding it if necessary. The simplest solution is therefore, during a reorg, to reparse only the block(s) concerned and then rebuild the `balance` table. I tested the method by adding a `--testbookindex` parameter and it works fine, see: https://github.com/CounterpartyXCP/counterparty-lib/pull/1322/commits/de4400a8060a3c7f4f496f5048fac3be59520e2d. I think we should replace undolog with this method.

**Comment by ouziel-slama** [comment]
A second solution is to add a `block_index` field in the `balance` table and therefore keep the balance history. This means that to have the current balance you have to look for the most recent `block_index`. So during a reorg we can clean this table like the others. I think I prefer this solution.

**Comment by adamkrellenstein** [comment]
Ooof, I can't believe I approved the `undolog` design... Agreed 100% @ouziel-slama.

**Comment by adamkrellenstein** [comment]
done
