### ISSUE TITLE
`Counterparty database is behind backend`

### ISSUE THREAD

**Issue by cryptonaut420** [CounterpartyXCP/counterparty-lib#692]
I haven't really noticed this happen much before, but I am getting it all the time lately (at least, on my localhost instance). Seems like almost every time a new block is found on the network, the counterparty API becomes completely unavailable and just constantly throws the "database is behind backend" errors. Can't even look at balances or asset info or anything, and can sometimes take several minutes before it becomes available again. Kind of a pain for scripts/applications which regularly poll the API..

Experiencing this on V9.49.3 BTW

Any ideas?

**Comment by adamkrellenstein** [comment]
@cryptonaut420, yeah, for a while the API status poller, which checks if the database is caught up with the blockchain, wasn't working correctly.  That problem was fixed here: https://github.com/CounterpartyXCP/counterpartyd/commit/9c184d924219f95459213e3534f6352a1426e921. So that explains why this wasn't a problem before.

I don't know the best way to handle this situation, however. The basic idea behind the current logic is that it's of the utmost importance that the API always give the most up-to-date information possible. So when a new block shows up on the Bitcoin network, the API server will throw that error until the server has fully processed the new block. If that takes too long, the retry logic in an API client can timeout.

It's been a while since we've done any speed optimizations to block parsing, so maybe that's the correct fix? Another thing to do would be to be more generous in considerations of being 'up-to-date'. (E.g., if it's been more than two minutes since the last block showed up, *then*, throw the error?)

**Comment by ouziel-slama** [comment]
> it's of the utmost importance that the API always give the most up-to-date information possible.

I think it's related with https://github.com/CounterpartyXCP/counterpartyd/issues/677 and I only half agree with this statement.
IMHO the most important is that the API returns the `block_time` of the last parsed block, and eventually the `block_time` the of last block in the backend. We don't always need to have an up-to-date database, indeed in most cases (for `send` transactions) a database with the correct balance for the source address is enough.

**Comment by cryptonaut420** [comment]
I think both including block_time (and also bitcoind_block_time or something) and optimizing parsing speed in general could both be good solutions. Plus faster parse speed means faster re-parsing and faster initial database build time, which is nice.  IMO it shouldn't just completely lock you out when it's in the middle of parsing a new block, it would be better to always get whatever data is available, but also always be able to know if what you are looking at is at the most recent version available (i.e providing block heights to compare, or just a blocks_remaining field to show how far behind it is)

**Comment by karlkeefer** [comment]
We are getting a handful of 525 errors when we query the API via counterblockd that seem to point to the same issue, might just be from `9.49.1`

I like the idea of including how far behind it is - makes for a very convenient test in the app layer `if (!block_parses_remaining)`

**Comment by adamkrellenstein** [comment]
If I'm reading this line right, you should only see this error if your database is *more* than one block behind the blockchain. That state should only occur if the Counterparty server is processing blocks more slowly than blocks are appearing. Of course, sometimes blocks appear quickly in succession by chance. Should this condition be changed to 'if the last block appeared more than 10 minutes ago *and* is at least two blocks ahead'?

You can currently get the block time of the last block with `get_running_info`. Are people suggesting that we return that value along with every API call? (I don't like that idea at all. Especially because block times are very unreliable in principle.)

@ouziel-slama, there's no way to check that you have the correct balance of any particular address *unless* you've parsed every available block.

**Comment by karlkeefer** [comment]
@adamkrellenstein that sounds right, otherwise we'd be seeing these 525's a lot more often than we currently are - it probably is only catching us when the block time is only 1 or 2 minutes which happens several times a day.

These would be significantly reduced if block parsing is a lot faster, but I'm not sure how much work is required to eek out the required performance gains there.

Our issue sounds a little different than @ouziel-slama -  ours is coming from [counterblockd](https://github.com/CounterpartyXCP/counterblock/blob/cd11ccf6e18c5adcb14952286c46bc30390f4575/lib/blockfeed.py#L24).

**Comment by ouziel-slama** [comment]
@adamkrellenstein :
> there's no way to check that you have the correct balance of any particular address unless you've parsed every available block.

Right.. but what I said, is that you don't always need to **check** if you have the correct balance..
If I have an address with some XCP, with no orders, no bets, no contracts, etc.. there is no reason that my balance changes *unless* someone have my private key.

**Comment by ouziel-slama** [comment]
> Are people suggesting that we return that value along with every API call? (I don't like that idea at all. Especially because block times are very unreliable in principle.)

Yep! I think that every API call should return the last parsed block. Even if `get_running_info` returns this information, because is an information needed for each request. I agree with you that the `block_time` is not reliable but the last block height is enough.
I don't like so much the idea of `block_parses_remaining` because (like in the actual situation) you assume that the backend is always up to date. But if you **really** want to check if the database is up-to-date, you need to check the last block against another backend. However, could be useful to have also the last block of the backend but not essential IMHO.

**Comment by cryptonaut420** [comment]
Just a quick update on this - I'm still occasionally getting this "database behind backend" error even with the latest v9.51.1

**Comment by robby-dermody** [comment]
Closing, given all of the recent performance updates made. Please reopen if still an issue

**Comment by cryptonaut420** [comment]
+1 latest versions run much more smoothly
