### ISSUE TITLE
ensure utxo reuse is prevented when constructing new transactions 

### ISSUE THREAD

**Issue by David-R-Allen** [CounterpartyXCP/counterparty-lib#875]
Counterparty frequently constructs transactions that are double spends or are inexplicably rejected by Bitcoin Core's broadcast function. Poloniex track inputs manually and have two fallbacks for broadcasting, but even so, sometimes the transactions never propagate.

**Comment by robby-dermody** [comment]
Note that it's possible that this happens when there are a relative lot of outbound send requests being made, and counterparty-lib may end up reusing utxos when constructing new transactions. I have a branch 'utxocache' that needs to be tested, that may address this issue. It's between who can get to it first, @rubensayshi or I (or anyone else that wants to help out :)

**Comment by robby-dermody** [comment]
closing as this is in `develop`
