### ISSUE TITLE
Testnet BTC balance broadcast error

### ISSUE THREAD

**Issue by jdogresorg** [CounterpartyXCP/counterparty-lib#927]
I believe there is an issue in counterparty-lib on testnet with sending longer broadcasts. Short broadcasts seem to work fine, but sending a longer broadcast results in a BTC balance error which prevents sending the broadcast.

**Here you can see my balance is 42+ BTC**
![screenshot1](https://cloud.githubusercontent.com/assets/376028/17828273/ec69effc-6641-11e6-9bec-e8de4cc81e00.png)

**Here you can see the broadcast that fails.**
![screenshot2](https://cloud.githubusercontent.com/assets/376028/17828274/ee8bacee-6641-11e6-924e-0d0ad431ec85.png)

**Here is the error message indicating that I do not have enough BTC to cover the transaction.**
![screenshot3](https://cloud.githubusercontent.com/assets/376028/17828276/f0814338-6641-11e6-8000-cd0ff4b51024.png)
##

**Comment by unsystemizer** [comment]
I think this is the same issue in counterparty-lib as when you try to use `issuance` and use too long asset description, instead of catching that error the command goes through and you get this unrelated error.

It's not only testnet, I think.

Also, while I was facing this "insufficient BTC" problem I didn't expect that this could be the reason because few months back the length issue was going to be fixed. But I rechecked now and it's been fixed, but so far only in `develop`:
https://github.com/CounterpartyXCP/counterparty-lib/pull/857

**Comment by jdogresorg** [comment]
I tested on mainnet before creating this issue and the broadcast that failed on testnet worked fine on mainnet.

https://counterpartychain.io/transaction/2f9664e37b297468c95876b0d89c59633dcb3a65ce5de8630d003432ce7b11ac
