### ISSUE TITLE
Fednode install not working if Mongodb is already installed

### ISSUE THREAD

**Issue by got3nks** [CounterpartyXCP/counterparty-lib#947]
Fednode installation fails if Mongodb is already installed:

`Cannot install, as it appears a process is already listening on host port 27017`

I guess it should rather use the existing Mongodb installation if available.

**Comment by unsystemizer** [comment]
I ran into this as well. Uninstall MongoDB if you don't use it for other things, then install FedNode.
Or stop MongoDB service before you install FedNode.

**Comment by got3nks** [comment]
I can't uninstall MongoDB as we are currently using it for other purposes.
If I stop MongoDB and try to install FedNode, would it re-install / wipe MongoDB databases?

**Comment by unsystemizer** [comment]
You don't have to uninstall or permanently stop it, you just need to stop it during installation.
But since you're using it for another production purpose, you should deal with this more carefully.
If you stop MongoDB and install FedNode, I don't think it will do anything bad to your existing DB (unless it has the same name).  However, since fednode.py runs on autopilot, it's never a good idea to run it unless you check the script every time there's an update or have a separate test system.

I suggest you devise a plan that works for your environment. 

You could hack the Fed Node install script to make it work well within your existing environment. For example, options in some of these lines could be changed.
https://github.com/CounterpartyXCP/federatednode/blob/master/fednode.py#L221
https://github.com/CounterpartyXCP/federatednode/blob/master/docker-compose.tmpl.yml#L158
This is possible but not ideal because you'd have to do that for every update. If you can hack it and submit a pull request here, then you'd have less issues in the future.

IMO the best way is make MongoDB run in a container that listens only on the bridge network (i.e. the network that links containers, so that counterblock and Counterwallet can get it it, but nothing else). That way these two wouldn't try to access the host network and see your other MongoDB, and at the same time they could access the FedNode MongoDB container. 

Whatever you try, don't use the production machine to try :-) 

Maybe @robby-dermody can tell us what he recommends.

**Comment by got3nks** [comment]
Now failing with a different error

ERROR: Failed to program FILTER chain: iptables failed: iptables --wait -I FORWARD -o br-ea7b6a105bd0 -j DOCKER: iptables v1.4.21: Couldn't load target `DOCKER':No such file or directory

**Comment by unsystemizer** [comment]
I checked on my FedNode:

* Mongo on the host is bound to localhost and "eth1"
* Mongo in counterblock container is listening on a docker network (only), which is `federatednode_default`, while `bridge` is its gateway which is likely why .

```
NETWORK ID          NAME                    DRIVER              SCOPE
81550c464f16        bridge                  bridge              local
f5ca8b371d40        federatednode_default   bridge              local
7e422f6a72ad        host                    host                local
1a40496e9747        none                    null                local
```

I just noticed in fednode.py, there's an option to restrict the MongoDB interface and the default is "all".
You could try with `--mongodb-interface bridge` (or `federatednode_default`) to avoid listening on 127.0.0.1 and that could solve your problem.

```
    parser_install.add_argument("--mongodb-interface", default="127.0.0.1",
        help="Bind mongo to this host interface. Localhost by default, enter 0.0.0.0 for all host interfaces.")
```
